name: openci_runner
description: Open CI VM runner
version: 0.6.3
homepage: https://open-ci.io
repository: https://github.com/open-ci-io/openci_runner

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  dart_firebase_admin: ^0.3.0
  dartssh2: ^2.8.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.5
  process_run: ^0.13.3
  pub_updater: ^0.3.0
  uuid: ^4.2.1

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  melos: ^3.4.0
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  openci_runner:
